/**
 * NimbusOS — Network Services API
 * SMB, SSH, FTP, NFS, WebDAV, DNS, Certs, Proxy, Portal, RemoteAccess, DDNS, UPnP, Firewall
 */
const { execSync, exec } = require('child_process');
const fs = require('fs');
const path = require('path');
const os = require('os');
const http = require('http');
const dgram = require('dgram');
const { URL } = require('url');
const { NIMBUS_ROOT, CONFIG_DIR, getSessionUser, run, readFile, formatBytes } = require('./shared.cjs');
const { getShares, saveShares } = require('./shares.cjs');

// ═══════════════════════════════════
// Native Apps API
// ═══════════════════════════════════
// ═══════════════════════════════════
// SMB / Samba Service API
// ═══════════════════════════════════
const SMB_CONFIG_FILE = path.join(CONFIG_DIR, 'smb.json');

function getSmbConfig() {
  try {
    if (fs.existsSync(SMB_CONFIG_FILE)) {
      return JSON.parse(fs.readFileSync(SMB_CONFIG_FILE, 'utf-8'));
    }
  } catch {}
  // Defaults
  return {
    workgroup: 'WORKGROUP',
    serverString: 'NimbusOS NAS',
    minProtocol: 'SMB2',
    maxProtocol: 'SMB3',
    guestAccess: false,
    recycleBin: true,
    auditLog: false,
    maxConnections: 0,       // 0 = unlimited
    enableNetbios: true,
  };
}

function saveSmbConfig(config) {
  fs.writeFileSync(SMB_CONFIG_FILE, JSON.stringify(config, null, 2));
}

function getSmbStatus() {
  // smbd lives in /usr/sbin which may not be in Node's PATH
  // Use multiple detection methods
  const installed = !!(
    run('which smbd 2>/dev/null') ||
    run('test -x /usr/sbin/smbd && echo yes') ||
    run('dpkg -l samba 2>/dev/null | grep -q "^ii" && echo yes') ||
    run('systemctl list-unit-files smbd.service 2>/dev/null | grep -q smbd && echo yes')
  );
  const running = run('systemctl is-active smbd 2>/dev/null') === 'active';
  
  // Try to get connected clients
  let clients = [];
  const smbstatus = run('smbstatus --shares --json 2>/dev/null');
  if (smbstatus) {
    try {
      const parsed = JSON.parse(smbstatus);
      clients = (parsed.sessions || []).map(s => ({
        user: s.username || '?',
        machine: s.remote_machine || s.hostname || '?',
        ip: s.remote_address || '?',
        share: s.service || '?',
        connected: s.signing || '?',
      }));
    } catch {}
  }
  // Fallback: text smbstatus
  if (clients.length === 0) {
    const raw = run('smbstatus -b 2>/dev/null');
    if (raw) {
      const lines = raw.split('\n').filter(l => l.match(/^\d+/));
      clients = lines.map(l => {
        const parts = l.trim().split(/\s+/);
        return {
          pid: parts[0] || '',
          user: parts[1] || '?',
          group: parts[2] || '',
          machine: parts[3] || '?',
          ip: parts[4] ? parts[4].replace(/[()]/g, '') : '?',
        };
      });
    }
  }

  // Get lock info
  let lockedFiles = 0;
  const locks = run('smbstatus -L 2>/dev/null');
  if (locks) {
    lockedFiles = (locks.match(/^\d+/gm) || []).length;
  }

  return {
    installed,
    running,
    clients,
    clientCount: clients.length,
    lockedFiles,
    port: 445,
    version: run('smbd --version 2>/dev/null') || null,
  };
}

function fixSharePermissions(shares) {
  for (const share of shares) {
    if (!share.path || !fs.existsSync(share.path)) continue;
    // Get first rw user as owner, fallback to 'nobody'
    const perms = share.permissions || {};
    const rwUsers = Object.entries(perms).filter(([, v]) => v === 'rw').map(([k]) => k);
    const owner = rwUsers[0] || 'nobody';
    // Ensure owner exists in Linux
    if (owner !== 'nobody') ensureLinuxUser(owner);
    // Set ownership recursively: owner:nimbus with setgid
    run(`sudo chown -R ${owner}:nimbus "${share.path}" 2>/dev/null`);
    run(`sudo chmod -R 2775 "${share.path}" 2>/dev/null`);
  }
}

function generateSmbConf(config, shares) {
  const lines = [
    '# Generated by NimbusOS — do not edit manually',
    `# Last updated: ${new Date().toISOString()}`,
    '',
    '[global]',
    `   workgroup = ${config.workgroup}`,
    `   server string = ${config.serverString}`,
    `   server min protocol = ${config.minProtocol}`,
    `   server max protocol = ${config.maxProtocol}`,
    '   security = user',
    `   map to guest = ${config.guestAccess ? 'Bad User' : 'Never'}`,
    '   dns proxy = no',
    '   log file = /var/log/samba/log.%m',
    '   max log size = 1000',
    '   logging = file',
    `   disable netbios = ${config.enableNetbios ? 'no' : 'yes'}`,
    `   max connections = ${config.maxConnections}`,
    '',
  ];

  if (config.recycleBin) {
    lines.push('   # Recycle bin (global defaults)');
    lines.push('   vfs objects = recycle');
    lines.push('   recycle:repository = .recycle/%U');
    lines.push('   recycle:keeptree = yes');
    lines.push('   recycle:versions = yes');
    lines.push('');
  }

  // Generate share sections from NimbusOS shares
  for (const share of shares) {
    const smbEnabled = share.smb !== false; // opt-out model
    if (!smbEnabled) continue;

    // Build valid users list
    const perms = share.permissions || {};
    const rwUsers = Object.entries(perms).filter(([, v]) => v === 'rw').map(([k]) => k);
    const roUsers = Object.entries(perms).filter(([, v]) => v === 'ro').map(([k]) => k);
    const allUsers = [...rwUsers, ...roUsers];

    lines.push(`[${share.displayName || share.name}]`);
    lines.push(`   comment = ${share.description || share.displayName || share.name}`);
    lines.push(`   path = ${share.path}`);
    lines.push(`   browseable = yes`);
    lines.push(`   read only = ${rwUsers.length === 0 ? 'yes' : 'no'}`);
    if (allUsers.length > 0) {
      lines.push(`   valid users = ${allUsers.join(' ')}`);
    }
    if (rwUsers.length > 0) {
      lines.push(`   write list = ${rwUsers.join(' ')}`);
    }
    if (config.guestAccess) {
      lines.push('   guest ok = yes');
    }
    lines.push('');
  }

  return lines.join('\n');
}

// ═══════════════════════════════════
// SSH API
// ═══════════════════════════════════
// ═══════════════════════════════════
// DDNS API
// ═══════════════════════════════════
const DDNS_CONFIG_FILE = path.join(CONFIG_DIR, 'ddns.json');
const DDNS_LOG_FILE = path.join(CONFIG_DIR, 'ddns.log');

function getDdnsConfig() {
  try { if (fs.existsSync(DDNS_CONFIG_FILE)) return JSON.parse(fs.readFileSync(DDNS_CONFIG_FILE, 'utf-8')); } catch {}
  return { enabled: false, provider: '', domain: '', token: '', username: '', interval: 5 };
}
function saveDdnsConfig(cfg) { fs.writeFileSync(DDNS_CONFIG_FILE, JSON.stringify(cfg, null, 2)); }

function ddnsUpdate(cfg) {
  let url = '';
  const headers = {};
  const token = (cfg.token || '').trim();
  const domain = (cfg.domain || '').trim();
  if (cfg.provider === 'duckdns') {
    const subdomain = domain.replace('.duckdns.org', '');
    url = `https://www.duckdns.org/update?domains=${subdomain}&token=${token}&ip=`;
  } else if (cfg.provider === 'noip') {
    url = `https://dynupdate.no-ip.com/nic/update?hostname=${domain}`;
    headers['Authorization'] = 'Basic ' + Buffer.from(`${(cfg.username||'').trim()}:${token}`).toString('base64');
  } else if (cfg.provider === 'dynu') {
    url = `https://api.dynu.com/nic/update?hostname=${domain}&password=${token}`;
  } else if (cfg.provider === 'cloudflare') {
    // Cloudflare needs zone + record IDs, simplified: just log
    return { ok: false, error: 'Cloudflare requires zone/record setup — use API token in CLI' };
  } else if (cfg.provider === 'freedns') {
    url = `https://freedns.afraid.org/dynamic/update.php?${token}`;
  } else {
    return { ok: false, error: 'Unknown provider' };
  }

  try {
    const curlCmd = headers.Authorization
      ? `curl -fsSL -H "Authorization: ${headers.Authorization}" "${url}" 2>&1`
      : `curl -fsSL "${url}" 2>&1`;
    const result = execSync(curlCmd, { encoding: 'utf-8', timeout: 15000 });
    const logEntry = `[${new Date().toISOString()}] ${cfg.provider}: ${result.trim()}\n`;
    fs.appendFileSync(DDNS_LOG_FILE, logEntry);
    return { ok: true, response: result.trim() };
  } catch (err) {
    const logEntry = `[${new Date().toISOString()}] ${cfg.provider}: ERROR ${err.message}\n`;
    fs.appendFileSync(DDNS_LOG_FILE, logEntry);
    return { ok: false, error: err.message };
  }
}

function setupDdnsCron(cfg) {
  // Remove existing nimbusos ddns cron
  run('crontab -l 2>/dev/null | grep -v "nimbusos-ddns" | crontab - 2>/dev/null');
  if (!cfg.enabled) return;
  // Write update script
  const script = `#!/bin/bash\n# nimbusos-ddns\nnode -e "require('${path.join(INSTALL_DIR, 'server', 'index.cjs')}').ddnsUpdate && process.exit()" 2>/dev/null || curl -fsSL "${cfg.provider === 'duckdns' ? `https://www.duckdns.org/update?domains=${(cfg.domain||'').trim().replace('.duckdns.org','')}&token=${(cfg.token||'').trim()}&ip=` : ''}" > /dev/null 2>&1\n`;
  const scriptPath = path.join(CONFIG_DIR, 'ddns-update.sh');
  fs.writeFileSync(scriptPath, script);
  run(`chmod +x "${scriptPath}"`);
  // Add cron
  const cronLine = `*/${cfg.interval} * * * * ${scriptPath} # nimbusos-ddns`;
  run(`(crontab -l 2>/dev/null; echo "${cronLine}") | crontab - 2>/dev/null`);
}

function handleDdns(url, method, body, req) {
  const session = getSessionUser(req);
  if (!session) return { error: 'Not authenticated' };

  if (url === '/api/ddns/status' && method === 'GET') {
    const config = getDdnsConfig();
    const externalIp = run('curl -fsSL https://api.ipify.org 2>/dev/null') || run('curl -fsSL https://ifconfig.me 2>/dev/null') || '—';
    let lastLog = '';
    try {
      if (fs.existsSync(DDNS_LOG_FILE)) {
        const lines = fs.readFileSync(DDNS_LOG_FILE, 'utf-8').trim().split('\n');
        lastLog = lines[lines.length - 1] || '';
      }
    } catch {}
    return { config, externalIp: externalIp.trim(), lastLog };
  }

  if (url === '/api/ddns/config' && method === 'POST') {
    if (session.role !== 'admin') return { error: 'Admin required' };
    saveDdnsConfig(body);
    setupDdnsCron(body);
    return { ok: true };
  }

  if (url === '/api/ddns/test' && method === 'POST') {
    if (session.role !== 'admin') return { error: 'Admin required' };
    const cfg = body.provider ? body : getDdnsConfig();
    return ddnsUpdate(cfg);
  }

  if (url === '/api/ddns/logs' && method === 'GET') {
    try {
      if (fs.existsSync(DDNS_LOG_FILE)) {
        const log = fs.readFileSync(DDNS_LOG_FILE, 'utf-8');
        return { log };
      }
    } catch {}
    return { log: '' };
  }

  return null;
}

// ═══════════════════════════════════
// Web Portal (port config) API
// ═══════════════════════════════════
function handlePortal(url, method, body, req) {
  const session = getSessionUser(req);
  if (!session) return { error: 'Not authenticated' };

  if (url === '/api/portal/status' && method === 'GET') {
    const currentPort = PORT;
    const httpsEnabled = !!process.env.NIMBUS_HTTPS;
    const httpsPort = process.env.NIMBUS_HTTPS_PORT || '5001';
    return { httpPort: currentPort, httpsEnabled, httpsPort };
  }

  if (url === '/api/portal/config' && method === 'POST') {
    if (session.role !== 'admin') return { error: 'Admin required' };
    const { httpPort, httpsPort } = body;
    
    // Validate ports
    const hp = parseInt(httpPort);
    const hsp = parseInt(httpsPort);
    if (hp && (hp < 1 || hp > 65535)) return { error: 'Invalid HTTP port' };
    if (hsp && (hsp < 1 || hsp > 65535)) return { error: 'Invalid HTTPS port' };
    
    // Update env file
    const envFile = '/etc/nimbusos/nimbusos.env';
    if (fs.existsSync(envFile)) {
      let env = fs.readFileSync(envFile, 'utf-8');
      if (hp) env = env.replace(/NIMBUS_PORT=\d+/, `NIMBUS_PORT=${hp}`);
      if (hsp) {
        if (env.includes('NIMBUS_HTTPS_PORT=')) {
          env = env.replace(/NIMBUS_HTTPS_PORT=\d+/, `NIMBUS_HTTPS_PORT=${hsp}`);
        } else {
          env += `\nNIMBUS_HTTPS_PORT=${hsp}\n`;
        }
      }
      fs.writeFileSync(envFile, env);
    }
    
    // Update systemd and firewall
    if (hp && hp !== PORT) {
      run(`sudo ufw allow ${hp}/tcp comment 'NimbusOS Web UI' 2>/dev/null`);
    }
    
    
    // Update nginx HTTPS proxy_pass if remote access is configured
    const nginxHttpsConf = '/etc/nginx/sites-available/nimbusos-https.conf';
    if (hp && fs.existsSync(nginxHttpsConf)) {
      try {
        let conf = fs.readFileSync(nginxHttpsConf, 'utf-8');
        conf = conf.replace(/proxy_pass http:\/\/127\.0\.0\.1:\d+;/, `proxy_pass http://127.0.0.1:${hp};`);
        fs.writeFileSync(nginxHttpsConf, conf);
        run('sudo nginx -t 2>/dev/null && sudo systemctl reload nginx 2>/dev/null');
      } catch {}
    }
    return { ok: true, needsRestart: true, message: `Port will change to ${hp || PORT} after restart. Run: sudo systemctl restart nimbusos` };
  }

  return null;
}

// ═══════════════════════════════════
// Reverse Proxy (Nginx) API
// ═══════════════════════════════════
const PROXY_CONFIG_FILE = path.join(CONFIG_DIR, 'proxy-rules.json');
const NGINX_SITES = '/etc/nginx/sites-available';
const NGINX_ENABLED = '/etc/nginx/sites-enabled';

function getProxyRules() {
  try { if (fs.existsSync(PROXY_CONFIG_FILE)) return JSON.parse(fs.readFileSync(PROXY_CONFIG_FILE, 'utf-8')); } catch {}
  return [];
}
function saveProxyRules(rules) { fs.writeFileSync(PROXY_CONFIG_FILE, JSON.stringify(rules, null, 2)); }

function generateNginxProxyConf(rule) {
  const upstreamName = rule.domain.replace(/[^a-z0-9]/g, '_');
  let conf = '';
  
  if (rule.ssl && rule.certPath) {
    // HTTPS server block
    conf += `server {\n`;
    conf += `    listen 443 ssl http2;\n`;
    conf += `    listen [::]:443 ssl http2;\n`;
    conf += `    server_name ${rule.domain};\n\n`;
    conf += `    ssl_certificate ${rule.certPath};\n`;
    conf += `    ssl_certificate_key ${rule.keyPath};\n`;
    conf += `    ssl_protocols TLSv1.2 TLSv1.3;\n`;
    conf += `    ssl_ciphers HIGH:!aNULL:!MD5;\n\n`;
    conf += `    location / {\n`;
    conf += `        proxy_pass http://${rule.target};\n`;
    conf += `        proxy_set_header Host $host;\n`;
    conf += `        proxy_set_header X-Real-IP $remote_addr;\n`;
    conf += `        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n`;
    conf += `        proxy_set_header X-Forwarded-Proto $scheme;\n`;
    conf += `        proxy_http_version 1.1;\n`;
    conf += `        proxy_set_header Upgrade $http_upgrade;\n`;
    conf += `        proxy_set_header Connection "upgrade";\n`;
    conf += `        proxy_buffering off;\n`;
    conf += `        proxy_request_buffering off;\n`;
    conf += `    }\n`;
    conf += `}\n\n`;
    // HTTP → HTTPS redirect
    conf += `server {\n`;
    conf += `    listen 80;\n    listen [::]:80;\n`;
    conf += `    server_name ${rule.domain};\n`;
    conf += `    return 301 https://$server_name$request_uri;\n`;
    conf += `}\n`;
  } else {
    // HTTP only
    conf += `server {\n`;
    conf += `    listen 80;\n    listen [::]:80;\n`;
    conf += `    server_name ${rule.domain};\n\n`;
    conf += `    location / {\n`;
    conf += `        proxy_pass http://${rule.target};\n`;
    conf += `        proxy_set_header Host $host;\n`;
    conf += `        proxy_set_header X-Real-IP $remote_addr;\n`;
    conf += `        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n`;
    conf += `        proxy_set_header X-Forwarded-Proto $scheme;\n`;
    conf += `        proxy_http_version 1.1;\n`;
    conf += `        proxy_set_header Upgrade $http_upgrade;\n`;
    conf += `        proxy_set_header Connection "upgrade";\n`;
    conf += `    }\n`;
    conf += `}\n`;
  }
  return conf;
}

function applyProxyRules(rules) {
  // Remove old nimbusos proxy rule files
  const existing = run(`ls ${NGINX_SITES}/nimbusos-proxy-*.conf 2>/dev/null`) || '';
  for (const f of existing.split('\n').filter(Boolean)) {
    const base = path.basename(f);
    fs.unlinkSync(f);
    try { fs.unlinkSync(path.join(NGINX_ENABLED, base)); } catch {}
  }
  
  // Generate new configs
  for (const rule of rules) {
    if (!rule.enabled) continue;
    const filename = `nimbusos-proxy-${rule.domain.replace(/[^a-z0-9.-]/g, '_')}.conf`;
    const conf = generateNginxProxyConf(rule);
    fs.writeFileSync(path.join(NGINX_SITES, filename), conf);
    run(`ln -sf ${path.join(NGINX_SITES, filename)} ${NGINX_ENABLED}/${filename}`);
  }
  
  // Test and reload
  const test = run('sudo nginx -t 2>&1');
  if (test && test.includes('failed')) {
    return { ok: false, error: 'Nginx config test failed', detail: test };
  }
  run('sudo systemctl reload nginx 2>/dev/null');
  return { ok: true };
}

function handleProxy(url, method, body, req) {
  const session = getSessionUser(req);
  if (!session) return { error: 'Not authenticated' };

  if (url === '/api/proxy/status' && method === 'GET') {
    const installed = !!(run('which nginx 2>/dev/null') || run('test -x /usr/sbin/nginx && echo yes'));
    const running = run('systemctl is-active nginx 2>/dev/null') === 'active';
    const version = run('nginx -v 2>&1') || null;
    const rules = getProxyRules();
    return { installed, running, version, rules };
  }

  // POST /api/proxy/rules — save all rules
  if (url === '/api/proxy/rules' && method === 'POST') {
    if (session.role !== 'admin') return { error: 'Admin required' };
    const { rules } = body;
    if (!Array.isArray(rules)) return { error: 'rules array required' };
    saveProxyRules(rules);
    const result = applyProxyRules(rules);
    return result;
  }

  // POST /api/proxy/add — add a single rule
  if (url === '/api/proxy/add' && method === 'POST') {
    if (session.role !== 'admin') return { error: 'Admin required' };
    const { domain, target, ssl } = body;
    if (!domain || !target) return { error: 'Domain and target required' };
    
    const rules = getProxyRules();
    if (rules.find(r => r.domain === domain)) return { error: 'Domain already exists' };
    
    const rule = { 
      domain, target, ssl: !!ssl, enabled: true, 
      created: new Date().toISOString(),
      certPath: '', keyPath: '',
    };
    
    // Try to get cert if SSL enabled
    if (ssl) {
      const certDir = `/etc/letsencrypt/live/${domain}`;
      if (fs.existsSync(certDir)) {
        rule.certPath = `${certDir}/fullchain.pem`;
        rule.keyPath = `${certDir}/privkey.pem`;
      }
    }
    
    rules.push(rule);
    saveProxyRules(rules);
    const result = applyProxyRules(rules);
    return { ...result, rule };
  }

  // POST /api/proxy/delete — remove a rule
  if (url === '/api/proxy/delete' && method === 'POST') {
    if (session.role !== 'admin') return { error: 'Admin required' };
    const { domain } = body;
    let rules = getProxyRules();
    rules = rules.filter(r => r.domain !== domain);
    saveProxyRules(rules);
    const result = applyProxyRules(rules);
    return result;
  }

  // POST /api/proxy/toggle — enable/disable rule
  if (url === '/api/proxy/toggle' && method === 'POST') {
    if (session.role !== 'admin') return { error: 'Admin required' };
    const { domain } = body;
    const rules = getProxyRules();
    const rule = rules.find(r => r.domain === domain);
    if (!rule) return { error: 'Rule not found' };
    rule.enabled = !rule.enabled;
    saveProxyRules(rules);
    const result = applyProxyRules(rules);
    return result;
  }

  // POST /api/proxy/ssl — request cert for a proxy rule
  if (url === '/api/proxy/ssl' && method === 'POST') {
    if (session.role !== 'admin') return { error: 'Admin required' };
    const { domain, email } = body;
    if (!domain || !email) return { error: 'Domain and email required' };
    
    try {
      const log = execSync(
        `sudo certbot --nginx -d "${domain}" --non-interactive --agree-tos -m "${email}" --redirect 2>&1`,
        { encoding: 'utf-8', timeout: 120000 }
      );
      
      // Update rule with cert paths
      const rules = getProxyRules();
      const rule = rules.find(r => r.domain === domain);
      if (rule) {
        rule.ssl = true;
        rule.certPath = `/etc/letsencrypt/live/${domain}/fullchain.pem`;
        rule.keyPath = `/etc/letsencrypt/live/${domain}/privkey.pem`;
        saveProxyRules(rules);
        applyProxyRules(rules);
      }
      
      return { ok: true, log };
    } catch (err) {
      return { error: 'SSL request failed', log: err.stderr || err.message };
    }
  }

  return null;
}

function handleSsh(url, method, body, req) {
  const session = getSessionUser(req);
  if (!session) return { error: 'Not authenticated' };

  if (url === '/api/ssh/status' && method === 'GET') {
    const running = run('systemctl is-active sshd 2>/dev/null || systemctl is-active ssh 2>/dev/null') === 'active';
    const version = run('ssh -V 2>&1 | head -1') || null;

    // Parse sshd_config
    const config = {};
    const conf = readFile('/etc/ssh/sshd_config');
    if (conf) {
      const get = (key) => {
        const m = conf.match(new RegExp(`^\\s*${key}\\s+(.+)`, 'mi'));
        return m ? m[1].trim() : null;
      };
      config.port = get('Port') || '22';
      config.rootLogin = get('PermitRootLogin') || 'prohibit-password';
      config.passwordAuth = get('PasswordAuthentication') || 'yes';
      config.pubkeyAuth = get('PubkeyAuthentication') || 'yes';
      config.maxAuthTries = get('MaxAuthTries') || '6';
      config.x11Forwarding = get('X11Forwarding') || 'no';
    }

    // Active sessions
    let connectedUsers = [];
    const who = run('who 2>/dev/null');
    if (who) {
      connectedUsers = who.split('\n').filter(Boolean).map(line => {
        const parts = line.trim().split(/\s+/);
        return { user: parts[0], tty: parts[1], login: parts[2] + ' ' + (parts[3] || ''), from: (parts[4] || '').replace(/[()]/g, '') };
      });
    }

    return { running, version, config, connectedUsers, activeSessions: connectedUsers.length };
  }

  if (url === '/api/ssh/start' && method === 'POST') {
    if (session.role !== 'admin') return { error: 'Admin required' };
    try {
      execSync('sudo systemctl enable ssh sshd 2>/dev/null; sudo systemctl start sshd 2>/dev/null || sudo systemctl start ssh 2>/dev/null', { encoding: 'utf-8', timeout: 10000 });
      return { ok: true };
    } catch (err) { return { error: 'Failed', detail: err.message }; }
  }

  if (url === '/api/ssh/stop' && method === 'POST') {
    if (session.role !== 'admin') return { error: 'Admin required' };
    try {
      execSync('sudo systemctl stop sshd 2>/dev/null; sudo systemctl stop ssh 2>/dev/null; sudo systemctl disable ssh sshd 2>/dev/null', { encoding: 'utf-8', timeout: 10000 });
      return { ok: true };
    } catch (err) { return { error: 'Failed', detail: err.message }; }
  }

  return null;
}

// ═══════════════════════════════════
// FTP API
// ═══════════════════════════════════
function handleFtp(url, method, body, req) {
  const session = getSessionUser(req);
  if (!session) return { error: 'Not authenticated' };

  if (url === '/api/ftp/status' && method === 'GET') {
    const installed = !!(run('which vsftpd 2>/dev/null') || run('test -x /usr/sbin/vsftpd && echo yes') || run('which proftpd 2>/dev/null'));
    const running = run('systemctl is-active vsftpd 2>/dev/null') === 'active' || run('systemctl is-active proftpd 2>/dev/null') === 'active';
    const sftpAvailable = run('systemctl is-active sshd 2>/dev/null || systemctl is-active ssh 2>/dev/null') === 'active';
    const version = run('vsftpd -v 2>&1 | head -1') || run('proftpd -v 2>&1 | head -1') || null;

    // Parse vsftpd.conf
    const config = {};
    const conf = readFile('/etc/vsftpd.conf') || readFile('/etc/vsftpd/vsftpd.conf');
    if (conf) {
      const get = (key) => {
        const m = conf.match(new RegExp(`^\\s*${key}\\s*=\\s*(.+)`, 'mi'));
        return m ? m[1].trim() : null;
      };
      config.port = get('listen_port') || '21';
      config.anonymousEnable = get('anonymous_enable') || 'NO';
      config.localEnable = get('local_enable') || 'YES';
      config.writeEnable = get('write_enable') || 'NO';
      config.chrootLocalUser = get('chroot_local_user') || 'NO';
      config.sslEnable = get('ssl_enable') || 'NO';
      config.pasvMinPort = get('pasv_min_port') || '';
      config.pasvMaxPort = get('pasv_max_port') || '';
    }

    return { installed, running, sftpAvailable, version, config };
  }

  if (url === '/api/ftp/start' && method === 'POST') {
    if (session.role !== 'admin') return { error: 'Admin required' };
    try {
      execSync('sudo systemctl enable vsftpd 2>/dev/null; sudo systemctl start vsftpd 2>/dev/null || sudo systemctl start proftpd 2>/dev/null', { encoding: 'utf-8', timeout: 10000 });
      return { ok: true };
    } catch (err) { return { error: 'Failed', detail: err.message }; }
  }

  if (url === '/api/ftp/stop' && method === 'POST') {
    if (session.role !== 'admin') return { error: 'Admin required' };
    try {
      execSync('sudo systemctl stop vsftpd proftpd 2>/dev/null; sudo systemctl disable vsftpd proftpd 2>/dev/null', { encoding: 'utf-8', timeout: 10000 });
      return { ok: true };
    } catch (err) { return { error: 'Failed', detail: err.message }; }
  }

  return null;
}

// ═══════════════════════════════════
// NFS API
// ═══════════════════════════════════
function handleNfs(url, method, body, req) {
  const session = getSessionUser(req);
  if (!session) return { error: 'Not authenticated' };

  if (url === '/api/nfs/status' && method === 'GET') {
    const installed = !!(
      run('which nfsd 2>/dev/null') ||
      run('test -x /usr/sbin/rpc.nfsd && echo yes') ||
      run('dpkg -l nfs-kernel-server 2>/dev/null | grep -q "^ii" && echo yes') ||
      run('systemctl list-unit-files nfs-server.service 2>/dev/null | grep -q nfs && echo yes')
    );
    const running = run('systemctl is-active nfs-server 2>/dev/null') === 'active' || run('systemctl is-active nfs-kernel-server 2>/dev/null') === 'active';
    const version = run('cat /proc/fs/nfsd/versions 2>/dev/null') || null;

    // Parse /etc/exports
    let exports = [];
    const exportsFile = readFile('/etc/exports');
    if (exportsFile) {
      exports = exportsFile.split('\n')
        .filter(l => l.trim() && !l.trim().startsWith('#'))
        .map(line => {
          const parts = line.trim().split(/\s+/);
          const path = parts[0];
          const rest = parts.slice(1).join(' ');
          // Extract clients and options: "192.168.1.0/24(rw,sync)"
          const clientMatch = rest.match(/^([^\(]+)/);
          const optMatch = rest.match(/\(([^)]+)\)/);
          return {
            path,
            clients: clientMatch ? clientMatch[1].trim() : '*',
            options: optMatch ? optMatch[1] : 'defaults',
          };
        });
    }

    // Active clients
    let activeClients = [];
    const showmount = run('showmount --no-headers 2>/dev/null');
    if (showmount) {
      activeClients = showmount.split('\n').filter(Boolean).map(line => {
        const parts = line.trim().split(/\s+/);
        return { client: parts[0] || '?', export: parts[1] || '?' };
      });
    }

    return { installed, running, version, exports, activeClients };
  }

  if (url === '/api/nfs/start' && method === 'POST') {
    if (session.role !== 'admin') return { error: 'Admin required' };
    try {
      execSync('sudo systemctl enable nfs-server nfs-kernel-server 2>/dev/null; sudo systemctl start nfs-server 2>/dev/null || sudo systemctl start nfs-kernel-server 2>/dev/null', { encoding: 'utf-8', timeout: 15000 });
      return { ok: true };
    } catch (err) { return { error: 'Failed', detail: err.message }; }
  }

  if (url === '/api/nfs/stop' && method === 'POST') {
    if (session.role !== 'admin') return { error: 'Admin required' };
    try {
      execSync('sudo systemctl stop nfs-server nfs-kernel-server 2>/dev/null; sudo systemctl disable nfs-server nfs-kernel-server 2>/dev/null', { encoding: 'utf-8', timeout: 15000 });
      return { ok: true };
    } catch (err) { return { error: 'Failed', detail: err.message }; }
  }

  return null;
}

// ═══════════════════════════════════
// DNS API
// ═══════════════════════════════════
function getDnsStatus() {
  const result = { servers: [], search: [], method: 'unknown' };
  
  // Try systemd-resolved first
  const resolved = run('resolvectl status 2>/dev/null');
  if (resolved) {
    result.method = 'systemd-resolved';
    const dnsLines = resolved.match(/DNS Servers?:\s*(.+)/g) || [];
    for (const line of dnsLines) {
      const ips = line.replace(/DNS Servers?:\s*/, '').trim().split(/\s+/);
      result.servers.push(...ips.filter(ip => ip.match(/^\d/)));
    }
    const searchMatch = resolved.match(/DNS Domain:\s*(.+)/);
    if (searchMatch) result.search = searchMatch[1].trim().split(/\s+/);
  }
  
  // Fallback: /etc/resolv.conf
  if (result.servers.length === 0) {
    const resolv = readFile('/etc/resolv.conf');
    if (resolv) {
      result.method = 'resolv.conf';
      const nameservers = resolv.match(/^nameserver\s+(\S+)/gm) || [];
      result.servers = nameservers.map(l => l.replace('nameserver ', '').trim());
      const searchLine = resolv.match(/^search\s+(.+)/m);
      if (searchLine) result.search = searchLine[1].trim().split(/\s+/);
    }
  }
  
  // Deduplicate
  result.servers = [...new Set(result.servers)];
  return result;
}

function handleDns(url, method, body, req) {
  const session = getSessionUser(req);
  if (!session) return { error: 'Not authenticated' };

  if (url === '/api/dns/status' && method === 'GET') {
    return getDnsStatus();
  }

  if (url === '/api/dns/config' && method === 'POST') {
    if (session.role !== 'admin') return { error: 'Admin required' };
    const { servers, search } = body;
    if (!servers || !Array.isArray(servers)) return { error: 'servers array required' };

    // Try systemd-resolved first
    const useResolved = !!run('which resolvectl 2>/dev/null');
    if (useResolved) {
      // Get default interface
      const iface = run("ip route | grep default | awk '{print $5}' | head -1") || 'eth0';
      const dnsCmd = `sudo resolvectl dns ${iface} ${servers.join(' ')} 2>/dev/null`;
      run(dnsCmd);
      if (search && search.length > 0) {
        run(`sudo resolvectl domain ${iface} ${search.join(' ')} 2>/dev/null`);
      }
    }
    
    // Also write resolv.conf as fallback
    const lines = ['# Generated by NimbusOS'];
    if (search && search.length > 0) lines.push(`search ${search.join(' ')}`);
    for (const s of servers) lines.push(`nameserver ${s}`);
    
    try {
      fs.writeFileSync('/tmp/nimbus-resolv.conf', lines.join('\n') + '\n');
      run('sudo cp /tmp/nimbus-resolv.conf /etc/resolv.conf 2>/dev/null');
    } catch {}
    
    return { ok: true };
  }

  return null;
}

// ═══════════════════════════════════
// Certificates / Let's Encrypt API
// ═══════════════════════════════════
function handleCerts(url, method, body, req) {
  const session = getSessionUser(req);
  if (!session) return { error: 'Not authenticated' };

  if (url === '/api/certs/status' && method === 'GET') {
    const certbotInstalled = !!(
      run('which certbot 2>/dev/null') ||
      run('test -x /usr/bin/certbot && echo yes') ||
      run('snap list certbot 2>/dev/null | grep certbot && echo yes')
    );
    
    const certificates = [];
    if (certbotInstalled) {
      const raw = run('sudo certbot certificates 2>/dev/null');
      if (raw) {
        // Parse certbot output
        const blocks = raw.split(/Certificate Name:/);
        for (const block of blocks.slice(1)) {
          const nameMatch = block.match(/^\s*(\S+)/);
          const domainMatch = block.match(/Domains?:\s*(.+)/);
          const expiryMatch = block.match(/Expiry Date:\s*(\S+ \S+ \S+)/);
          const pathMatch = block.match(/Certificate Path:\s*(\S+)/);
          
          if (nameMatch) {
            const expiry = expiryMatch ? expiryMatch[1] : 'unknown';
            let daysLeft = -1;
            if (expiryMatch) {
              try {
                const expDate = new Date(expiryMatch[1]);
                daysLeft = Math.floor((expDate - Date.now()) / 86400000);
              } catch {}
            }
            
            certificates.push({
              name: nameMatch[1].trim(),
              domain: domainMatch ? domainMatch[1].trim() : nameMatch[1].trim(),
              expiry,
              daysLeft,
              valid: daysLeft > 0,
              path: pathMatch ? pathMatch[1].trim() : '',
              issuer: "Let's Encrypt",
            });
          }
        }
      }
    }
    
    // Also check for self-signed certs
    const selfSigned = run('ls /etc/ssl/certs/nimbus* 2>/dev/null');
    if (selfSigned) {
      for (const certPath of selfSigned.split('\n').filter(Boolean)) {
        const info = run(`openssl x509 -in "${certPath}" -noout -subject -enddate 2>/dev/null`);
        if (info) {
          const subMatch = info.match(/CN\s*=\s*(\S+)/);
          const endMatch = info.match(/notAfter=(.+)/);
          let daysLeft = -1;
          if (endMatch) {
            try { daysLeft = Math.floor((new Date(endMatch[1]) - Date.now()) / 86400000); } catch {}
          }
          certificates.push({
            name: subMatch ? subMatch[1] : 'Self-signed',
            domain: subMatch ? subMatch[1] : path.basename(certPath),
            expiry: endMatch ? endMatch[1].trim() : 'unknown',
            daysLeft,
            valid: daysLeft > 0,
            path: certPath,
            issuer: 'Self-signed',
          });
        }
      }
    }

    return { certbotInstalled, certificates };
  }

  // POST /api/certs/request — request new Let's Encrypt cert
  if (url === '/api/certs/request' && method === 'POST') {
    if (session.role !== 'admin') return { error: 'Admin required' };
    const { domain, email, method: certMethod } = body;
    if (!domain || !email) return { error: 'Domain and email required' };
    
    let cmd = `sudo certbot certonly --non-interactive --agree-tos -m "${email}"`;
    if (certMethod === 'standalone') {
      cmd += ` --standalone -d "${domain}"`;
    } else if (certMethod === 'webroot') {
      cmd += ` --webroot -w /var/www/html -d "${domain}"`;
    } else if (certMethod === 'dns') {
      cmd += ` --manual --preferred-challenges dns -d "${domain}"`;
    }
    
    try {
      const log = execSync(cmd + ' 2>&1', { encoding: 'utf-8', timeout: 120000 });
      return { ok: true, log };
    } catch (err) {
      return { error: 'Certificate request failed', log: err.stderr || err.stdout || err.message };
    }
  }

  // POST /api/certs/renew — renew specific cert
  if (url === '/api/certs/renew' && method === 'POST') {
    if (session.role !== 'admin') return { error: 'Admin required' };
    const { domain } = body;
    try {
      const log = execSync(`sudo certbot renew --cert-name "${domain}" --force-renewal 2>&1`,
        { encoding: 'utf-8', timeout: 120000 });
      return { ok: true, log };
    } catch (err) {
      return { error: 'Renewal failed', log: err.stderr || err.message };
    }
  }

  // POST /api/certs/delete — delete cert
  if (url === '/api/certs/delete' && method === 'POST') {
    if (session.role !== 'admin') return { error: 'Admin required' };
    const { domain } = body;
    try {
      run(`sudo certbot delete --cert-name "${domain}" --non-interactive 2>/dev/null`);
      return { ok: true };
    } catch {
      return { error: 'Delete failed' };
    }
  }

  return null;
}

// ═══════════════════════════════════
// Remote Access API (unified DDNS + SSL + HTTPS)
// ═══════════════════════════════════
const REMOTE_ACCESS_CONFIG = path.join(CONFIG_DIR, 'remote-access.json');

function getRemoteAccessConfig() {
  try {
    if (fs.existsSync(REMOTE_ACCESS_CONFIG)) {
      return JSON.parse(fs.readFileSync(REMOTE_ACCESS_CONFIG, 'utf-8'));
    }
  } catch {}
  return {
    ddns: { enabled: false, provider: 'duckdns', domain: '', token: '', username: '', interval: 5 },
    ssl: { enabled: false, email: '', method: 'dns' },
    https: { enabled: false, port: 5009 },
  };
}

function saveRemoteAccessConfig(cfg) {
  try {
    if (!fs.existsSync(CONFIG_DIR)) fs.mkdirSync(CONFIG_DIR, { recursive: true });
    fs.writeFileSync(REMOTE_ACCESS_CONFIG, JSON.stringify(cfg, null, 2));
    return true;
  } catch { return false; }
}

function getRemoteAccessStatus(cfg) {
  const result = {
    ddns: { working: false, externalIp: null },
    ssl: { valid: false, domain: null, expiry: null, daysLeft: null, certPath: null },
    https: { running: false, port: cfg.https?.port || 5009, enabled: cfg.https?.enabled || false },
    localIp: null,
    nimbusPort: parseInt(process.env.NIMBUS_PORT || '5000'),
  };

  // Check external IP
  try {
    result.ddns.externalIp = run('curl -fsSL --connect-timeout 5 https://api.ipify.org 2>/dev/null') ||
      run('curl -fsSL --connect-timeout 5 https://ifconfig.me 2>/dev/null');
  } catch {}

  // Check DDNS working
  const fullDomain = cfg.ddns?.fullDomain || cfg.ddns?.domain;
  if (cfg.ddns?.enabled && fullDomain) {
    try {
      const resolved = run(`dig +short ${fullDomain} 2>/dev/null`);
      if (resolved && result.ddns.externalIp && resolved.trim() === result.ddns.externalIp.trim()) {
        result.ddns.working = true;
      }
    } catch {}
    result.ddns = { ...result.ddns, ...cfg.ddns };
  }

  // Check SSL certificate
  if (fullDomain) {
    const certDir = `/etc/letsencrypt/live/${fullDomain}`;
    try {
      if (fs.existsSync(`${certDir}/fullchain.pem`)) {
        const certInfo = run(`openssl x509 -in ${certDir}/fullchain.pem -noout -enddate -subject 2>/dev/null`);
        if (certInfo) {
          const expiryMatch = certInfo.match(/notAfter=(.+)/);
          if (expiryMatch) {
            const expiry = new Date(expiryMatch[1]);
            const daysLeft = Math.floor((expiry - Date.now()) / 86400000);
            result.ssl = {
              valid: daysLeft > 0,
              domain: fullDomain,
              expiry: expiry.toISOString().split('T')[0],
              daysLeft,
              certPath: `${certDir}/fullchain.pem`,
              keyPath: `${certDir}/privkey.pem`,
            };
          }
        }
      }
    } catch {}
  }

  // Check HTTPS (nginx listening on the HTTPS port)
  if (cfg.https?.enabled) {
    const httpsPort = cfg.https.port || 5009;
    const listening = run(`ss -tlnp 2>/dev/null | grep ':${httpsPort} '`);
    result.https.running = !!listening;
    result.https.enabled = true;
  }

  // Local IP
  try {
    const ifaces = require('os').networkInterfaces();
    for (const name of Object.keys(ifaces)) {
      for (const iface of ifaces[name]) {
        if (iface.family === 'IPv4' && !iface.internal) {
          result.localIp = iface.address;
          break;
        }
      }
      if (result.localIp) break;
    }
  } catch {}

  return result;
}

function handleRemoteAccess(url, method, body, req) {
  const session = getSessionUser(req);
  if (!session) return { error: 'Not authenticated' };

  // GET /api/remote-access/status
  if (url === '/api/remote-access/status' && method === 'GET') {
    const cfg = getRemoteAccessConfig();
    return { ...getRemoteAccessStatus(cfg), config: cfg };
  }

  // POST /api/remote-access/configure — save full config
  if (url === '/api/remote-access/configure' && method === 'POST') {
    if (session.role !== 'admin') return { error: 'Admin required' };
    const cfg = getRemoteAccessConfig();
    if (body.ddns) cfg.ddns = { ...cfg.ddns, ...body.ddns };
    if (body.ssl) cfg.ssl = { ...cfg.ssl, ...body.ssl };
    if (body.https) cfg.https = { ...cfg.https, ...body.https };
    saveRemoteAccessConfig(cfg);

    // Also sync to the DDNS system (reuse existing ddns setup)
    if (cfg.ddns?.enabled) {
      try {
        const ddnsBody = { ...cfg.ddns };
        fs.writeFileSync(DDNS_CONFIG_FILE, JSON.stringify(ddnsBody, null, 2));
        setupDdnsCron(ddnsBody);
      } catch {}
    }

    return { ok: true };
  }

  // POST /api/remote-access/test-ddns
  if (url === '/api/remote-access/test-ddns' && method === 'POST') {
    if (session.role !== 'admin') return { error: 'Admin required' };
    return ddnsUpdate(body);
  }

  // POST /api/remote-access/request-ssl — with DNS challenge support
  if (url === '/api/remote-access/request-ssl' && method === 'POST') {
    if (session.role !== 'admin') return { error: 'Admin required' };
    const { domain, email, method: certMethod, provider, dnsToken } = body;
    if (!domain || !email) return { error: 'Domain and email required' };

    let cmd = `sudo certbot certonly --non-interactive --agree-tos -m "${email}"`;

    if (certMethod === 'dns') {
      if (provider === 'duckdns') {
        // DuckDNS DNS-01 challenge using certbot-dns-duckdns plugin
        // First try plugin, fallback to manual hook
        const pluginInstalled = run('pip3 show certbot-dns-duckdns 2>/dev/null') ||
          run('certbot plugins 2>/dev/null | grep duckdns');
        
        if (pluginInstalled) {
          // Use certbot-dns-duckdns plugin
          const credFile = path.join(CONFIG_DIR, 'duckdns-credentials.ini');
          fs.writeFileSync(credFile, `dns_duckdns_token = ${dnsToken}\n`, { mode: 0o600 });
          cmd += ` --authenticator dns-duckdns --dns-duckdns-credentials "${credFile}"`;
          cmd += ` --dns-duckdns-propagation-seconds 60 -d "${domain}"`;
        } else {
          // Use manual hooks with DuckDNS API
          const hookDir = path.join(CONFIG_DIR, 'certbot-hooks');
          if (!fs.existsSync(hookDir)) fs.mkdirSync(hookDir, { recursive: true });
          
          const subdomain = domain.replace('.duckdns.org', '');
          
          // Auth hook: set the TXT record via DuckDNS API
          const authHook = path.join(hookDir, 'duckdns-auth.sh');
          fs.writeFileSync(authHook, [
            '#!/bin/bash',
            `# DuckDNS DNS-01 auth hook for ${domain}`,
            `TOKEN="${dnsToken}"`,
            `DOMAIN="${subdomain}"`,
            `echo "Setting DuckDNS TXT record for _acme-challenge.$DOMAIN..."`,
            `curl -s "https://www.duckdns.org/update?domains=$DOMAIN&token=$TOKEN&txt=$CERTBOT_VALIDATION" > /dev/null`,
            `echo "Waiting 60s for DNS propagation..."`,
            `sleep 60`,
          ].join('\n'), { mode: 0o755 });

          // Cleanup hook: clear TXT record
          const cleanupHook = path.join(hookDir, 'duckdns-cleanup.sh');
          fs.writeFileSync(cleanupHook, [
            '#!/bin/bash',
            `TOKEN="${dnsToken}"`,
            `DOMAIN="${subdomain}"`,
            `curl -s "https://www.duckdns.org/update?domains=$DOMAIN&token=$TOKEN&txt=removed&clear=true" > /dev/null`,
          ].join('\n'), { mode: 0o755 });

          cmd += ` --manual --preferred-challenges dns`;
          cmd += ` --manual-auth-hook "${authHook}"`;
          cmd += ` --manual-cleanup-hook "${cleanupHook}"`;
          cmd += ` -d "${domain}"`;
        }
      } else if (provider === 'cloudflare') {
        // Cloudflare DNS plugin
        const credFile = path.join(CONFIG_DIR, 'cloudflare-credentials.ini');
        fs.writeFileSync(credFile, `dns_cloudflare_api_token = ${dnsToken}\n`, { mode: 0o600 });
        cmd += ` --dns-cloudflare --dns-cloudflare-credentials "${credFile}"`;
        cmd += ` --dns-cloudflare-propagation-seconds 30 -d "${domain}"`;
      } else {
        // Generic manual DNS (user will need to add TXT manually — but this path is for non-DNS providers)
        cmd += ` --manual --preferred-challenges dns -d "${domain}"`;
      }
    } else if (certMethod === 'standalone') {
      cmd += ` --standalone -d "${domain}"`;
    } else if (certMethod === 'webroot') {
      cmd += ` --webroot -w /var/www/html -d "${domain}"`;
    }

    try {
      const log = execSync(cmd + ' 2>&1', { encoding: 'utf-8', timeout: 180000 });
      
      // Update config to mark SSL as active
      const cfg = getRemoteAccessConfig();
      cfg.ssl = { ...cfg.ssl, enabled: true, domain };
      saveRemoteAccessConfig(cfg);
      
      return { ok: true, log };
    } catch (err) {
      return { error: 'Certificate request failed', log: err.stderr || err.stdout || err.message };
    }
  }

  // POST /api/remote-access/enable-https — configure nginx HTTPS block
  if (url === '/api/remote-access/enable-https' && method === 'POST') {
    if (session.role !== 'admin') return { error: 'Admin required' };
    const { port, domain, enabled } = body;
    const httpsPort = port || 5009;
    const cfg = getRemoteAccessConfig();
    const nimbusPort = parseInt(process.env.NIMBUS_PORT || '5000');

    if (enabled) {
      const certDir = `/etc/letsencrypt/live/${domain}`;
      if (!fs.existsSync(`${certDir}/fullchain.pem`)) {
        return { error: `No certificate found for ${domain}. Request one first (Step 2).` };
      }

      // Write nginx HTTPS server block
      const nginxConf = [
        `# NimbusOS HTTPS — managed by Remote Access panel`,
        `server {`,
        `    listen ${httpsPort} ssl http2;`,
        `    listen [::]:${httpsPort} ssl http2;`,
        `    server_name ${domain};`,
        ``,
        `    ssl_certificate ${certDir}/fullchain.pem;`,
        `    ssl_certificate_key ${certDir}/privkey.pem;`,
        `    ssl_protocols TLSv1.2 TLSv1.3;`,
        `    ssl_ciphers HIGH:!aNULL:!MD5;`,
        `    ssl_prefer_server_ciphers on;`,
        `    ssl_session_cache shared:SSL:10m;`,
        `    ssl_session_timeout 10m;`,
        ``,
        `    # HSTS`,
        `    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;`,
        ``,
        `    location / {`,
        `        proxy_pass http://127.0.0.1:${nimbusPort};`,
        `        proxy_set_header Host $host;`,
        `        proxy_set_header X-Real-IP $remote_addr;`,
        `        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;`,
        `        proxy_set_header X-Forwarded-Proto $scheme;`,
        `        proxy_http_version 1.1;`,
        `        proxy_set_header Upgrade $http_upgrade;`,
        `        proxy_set_header Connection "upgrade";`,
        `        proxy_buffering off;`,
        `        proxy_request_buffering off;`,
        `    }`,
        `}`,
      ].join('\n');

      try {
        fs.writeFileSync('/etc/nginx/sites-available/nimbusos-https.conf', nginxConf);
        run('ln -sf /etc/nginx/sites-available/nimbusos-https.conf /etc/nginx/sites-enabled/nimbusos-https.conf');
        
        // Open the port in UFW if active
        run(`sudo ufw allow ${httpsPort}/tcp comment "NimbusOS HTTPS" 2>/dev/null`);
        
        // Test and reload nginx
        const testResult = run('sudo nginx -t 2>&1');
        if (testResult && testResult.includes('failed')) {
          return { error: 'Nginx config test failed', log: testResult };
        }
        run('sudo systemctl reload nginx');

        cfg.https = { enabled: true, port: httpsPort };
        saveRemoteAccessConfig(cfg);
        return { ok: true, message: `HTTPS enabled on port ${httpsPort}` };
      } catch (err) {
        return { error: err.message };
      }
    } else {
      // Disable HTTPS
      try {
        run('rm -f /etc/nginx/sites-enabled/nimbusos-https.conf');
        run('sudo systemctl reload nginx');
        cfg.https = { enabled: false, port: httpsPort };
        saveRemoteAccessConfig(cfg);
        return { ok: true, message: 'HTTPS disabled' };
      } catch (err) {
        return { error: err.message };
      }
    }
  }

  return null;
}

// ═══════════════════════════════════
// WebDAV API
// ═══════════════════════════════════
const WEBDAV_CONFIG_FILE = path.join(CONFIG_DIR, 'webdav.json');

function getWebdavConfig() {
  try {
    if (fs.existsSync(WEBDAV_CONFIG_FILE)) {
      return JSON.parse(fs.readFileSync(WEBDAV_CONFIG_FILE, 'utf-8'));
    }
  } catch {}
  return {
    httpPort: '5005',
    httpsPort: '5006',
    maxUploadMB: 10240,
    requireAuth: true,
  };
}

function generateWebdavNginxConf() {
  const config = getWebdavConfig();
  const shares = getShares();
  const webdavShares = shares.filter(s => s.webdav);
  
  let locations = '';
  for (const share of webdavShares) {
    const sharePath = share.path || `/nimbus/pools/${share.pool}/shares/${share.name}`;
    locations += `
    location /${share.name} {
        alias ${sharePath};
        dav_methods PUT DELETE MKCOL COPY MOVE;
        dav_ext_methods PROPFIND OPTIONS;
        dav_access user:rw group:rw all:r;
        client_max_body_size ${config.maxUploadMB || 10240}m;
        autoindex on;
        create_full_put_path on;
    }
`;
  }
  
  if (!locations) {
    locations = `
    location / {
        return 200 'WebDAV server running. No shares enabled.';
        add_header Content-Type text/plain;
    }
`;
  }
  
  const conf = `# NimbusOS WebDAV — managed by WebDAV panel
server {
    listen ${config.httpPort || 5005};
    listen [::]:${config.httpPort || 5005};
    server_name _;
${locations}
}
`;
  
  fs.writeFileSync('/etc/nginx/sites-available/nimbusos-webdav.conf', conf);
  return conf;
}

function saveWebdavConfig(config) {
  fs.writeFileSync(WEBDAV_CONFIG_FILE, JSON.stringify(config, null, 2));
}

function handleWebdav(url, method, body, req) {
  const session = getSessionUser(req);
  if (!session) return { error: 'Not authenticated' };

  if (url === '/api/webdav/status' && method === 'GET') {
    const nginxInstalled = !!(run('which nginx 2>/dev/null') || run('test -x /usr/sbin/nginx && echo yes'));
    const installed = nginxInstalled;
    
    let running = false;
    let version = null;
    let server = 'Nginx';
    
    if (nginxInstalled) {
      // WebDAV is "running" if its site config is enabled in nginx
      running = fs.existsSync('/etc/nginx/sites-enabled/nimbusos-webdav.conf');
      version = run('nginx -v 2>&1 | head -1') || null;
    }

    const config = getWebdavConfig();
    const shares = getShares();
    const webdavShares = shares.map(s => ({
      name: s.name,
      displayName: s.displayName,
      path: s.path,
      pool: s.pool,
      webdavEnabled: s.webdav === true,
    }));

    return { installed, running, version, server, config, shares: webdavShares };
  }

  if (url === '/api/webdav/config' && method === 'POST') {
    if (session.role !== 'admin') return { error: 'Admin required' };
    const current = getWebdavConfig();
    const updated = { ...current, ...body };
    saveWebdavConfig(updated);
    return { ok: true, config: updated };
  }

  if (url === '/api/webdav/start' && method === 'POST') {
    if (session.role !== 'admin') return { error: 'Admin required' };
    try {
      // Generate/update WebDAV nginx config, then enable it
      generateWebdavNginxConf();
      run('sudo ln -sf /etc/nginx/sites-available/nimbusos-webdav.conf /etc/nginx/sites-enabled/ 2>/dev/null');
      const test = run('sudo nginx -t 2>&1');
      if (test && test.includes('failed')) {
        run('sudo rm -f /etc/nginx/sites-enabled/nimbusos-webdav.conf 2>/dev/null');
        return { error: 'Nginx config test failed', detail: test };
      }
      execSync('sudo systemctl reload nginx 2>/dev/null',
        { encoding: 'utf-8', timeout: 15000 });
      const config = getWebdavConfig();
      run(`sudo ufw allow ${config.httpPort || 5005}/tcp comment 'NimbusOS WebDAV' 2>/dev/null`);
      return { ok: true };
    } catch (err) {
      return { error: 'Failed to start', detail: err.message };
    }
  }

  if (url === '/api/webdav/stop' && method === 'POST') {
    if (session.role !== 'admin') return { error: 'Admin required' };
    try {
      // Disable WebDAV config only — never stop nginx (HTTPS depends on it)
      run('sudo rm -f /etc/nginx/sites-enabled/nimbusos-webdav.conf 2>/dev/null');
      execSync('sudo nginx -t 2>/dev/null && sudo systemctl reload nginx 2>/dev/null',
        { encoding: 'utf-8', timeout: 15000 });
      return { ok: true };
    } catch (err) {
      return { error: 'Failed to stop', detail: err.message };
    }
  }

  if (url === '/api/webdav/restart' && method === 'POST') {
    if (session.role !== 'admin') return { error: 'Admin required' };
    try {
      execSync('sudo nginx -t 2>/dev/null && sudo systemctl reload nginx 2>/dev/null',
        { encoding: 'utf-8', timeout: 15000 });
      return { ok: true };
    } catch (err) {
      return { error: 'Failed to restart', detail: err.message };
    }
  }

  // PUT /api/webdav/share/:name — toggle WebDAV on a share
  const shareToggle = url.match(/^\/api\/webdav\/share\/([a-zA-Z0-9_-]+)$/);
  if (shareToggle && method === 'PUT') {
    if (session.role !== 'admin') return { error: 'Admin required' };
    const name = shareToggle[1];
    const shares = getShares();
    const share = shares.find(s => s.name === name);
    if (!share) return { error: 'Share not found' };
    share.webdav = body.enabled !== false;
    saveShares(shares);
    // Regenerate and reload nginx config if WebDAV is running
    if (fs.existsSync('/etc/nginx/sites-enabled/nimbusos-webdav.conf')) {
      generateWebdavNginxConf();
      run('sudo nginx -t 2>/dev/null && sudo systemctl reload nginx 2>/dev/null');
    }
    return { ok: true, name, webdavEnabled: share.webdav };
  }

  return null;
}

function handleSmb(url, method, body, req) {
  const session = getSessionUser(req);
  if (!session) return { error: 'Not authenticated' };

  // GET /api/smb/status — full SMB status
  if (url === '/api/smb/status' && method === 'GET') {
    const config = getSmbConfig();
    const status = getSmbStatus();
    const shares = getShares();
    
    // Enrich shares with SMB-specific info
    const smbShares = shares.map(s => {
      const perms = s.permissions || {};
      const rwUsers = Object.entries(perms).filter(([, v]) => v === 'rw').map(([k]) => k);
      const roUsers = Object.entries(perms).filter(([, v]) => v === 'ro').map(([k]) => k);
      return {
        name: s.name,
        displayName: s.displayName,
        path: s.path,
        pool: s.pool,
        smbEnabled: s.smb !== false,
        rwUsers,
        roUsers,
        recycleBin: s.recycleBin !== false,
        description: s.description || '',
      };
    });

    return {
      ...status,
      config,
      shares: smbShares,
    };
  }

  // POST /api/smb/config — update SMB config (admin only)
  if (url === '/api/smb/config' && method === 'POST') {
    if (session.role !== 'admin') return { error: 'Admin required' };
    const current = getSmbConfig();
    const updated = { ...current, ...body };
    
    // Sanitize
    if (updated.workgroup) updated.workgroup = updated.workgroup.toUpperCase().replace(/[^A-Z0-9_-]/g, '');
    if (!['SMB2', 'SMB2_02', 'SMB2_10', 'SMB3', 'SMB3_00', 'SMB3_02', 'SMB3_11'].includes(updated.minProtocol)) {
      updated.minProtocol = 'SMB2';
    }
    if (!['SMB2', 'SMB2_02', 'SMB2_10', 'SMB3', 'SMB3_00', 'SMB3_02', 'SMB3_11'].includes(updated.maxProtocol)) {
      updated.maxProtocol = 'SMB3';
    }
    
    saveSmbConfig(updated);
    return { ok: true, config: updated };
  }

  // POST /api/smb/start — start smbd (admin only)
  if (url === '/api/smb/start' && method === 'POST') {
    if (session.role !== 'admin') return { error: 'Admin required' };
    try {
      // Generate config first
      const config = getSmbConfig();
      const shares = getShares();
      const conf = generateSmbConf(config, shares);
      
      // Fix permissions on all share directories
      fixSharePermissions(shares);
      
      // Write smb.conf
      try {
        run(`sudo cp /etc/samba/smb.conf /etc/samba/smb.conf.bak 2>/dev/null`);
        fs.writeFileSync('/tmp/nimbus-smb.conf', conf);
        run('sudo cp /tmp/nimbus-smb.conf /etc/samba/smb.conf');
      } catch {}
      
      execSync('sudo systemctl enable smbd nmbd 2>/dev/null; sudo systemctl start smbd nmbd 2>/dev/null || sudo systemctl start smbd 2>/dev/null', 
        { encoding: 'utf-8', timeout: 15000 });
      return { ok: true };
    } catch (err) {
      return { error: 'Failed to start SMB', detail: err.message };
    }
  }

  // POST /api/smb/stop — stop smbd (admin only)
  if (url === '/api/smb/stop' && method === 'POST') {
    if (session.role !== 'admin') return { error: 'Admin required' };
    try {
      execSync('sudo systemctl stop smbd nmbd 2>/dev/null; sudo systemctl disable smbd nmbd 2>/dev/null', 
        { encoding: 'utf-8', timeout: 15000 });
      return { ok: true };
    } catch (err) {
      return { error: 'Failed to stop SMB', detail: err.message };
    }
  }

  // POST /api/smb/restart — restart smbd (admin only)
  if (url === '/api/smb/restart' && method === 'POST') {
    if (session.role !== 'admin') return { error: 'Admin required' };
    try {
      const config = getSmbConfig();
      const shares = getShares();
      const conf = generateSmbConf(config, shares);
      
      // Fix permissions on all share directories
      fixSharePermissions(shares);
      
      try {
        fs.writeFileSync('/tmp/nimbus-smb.conf', conf);
        run('sudo cp /tmp/nimbus-smb.conf /etc/samba/smb.conf');
      } catch {}
      
      execSync('sudo systemctl restart smbd nmbd 2>/dev/null || sudo systemctl restart smbd 2>/dev/null', 
        { encoding: 'utf-8', timeout: 15000 });
      return { ok: true };
    } catch (err) {
      return { error: 'Failed to restart SMB', detail: err.message };
    }
  }

  // POST /api/smb/apply — regenerate smb.conf without restart (admin only)
  if (url === '/api/smb/apply' && method === 'POST') {
    if (session.role !== 'admin') return { error: 'Admin required' };
    try {
      const config = getSmbConfig();
      const shares = getShares();
      const conf = generateSmbConf(config, shares);
      
      // Fix permissions on all share directories
      fixSharePermissions(shares);
      
      fs.writeFileSync('/tmp/nimbus-smb.conf', conf);
      run('sudo cp /tmp/nimbus-smb.conf /etc/samba/smb.conf');
      // Reload without restart
      run('sudo smbcontrol all reload-config 2>/dev/null');
      return { ok: true, preview: conf };
    } catch (err) {
      return { error: 'Failed to apply config', detail: err.message };
    }
  }

  // GET /api/smb/preview — preview generated smb.conf (admin only)
  if (url === '/api/smb/preview' && method === 'GET') {
    if (session.role !== 'admin') return { error: 'Admin required' };
    const config = getSmbConfig();
    const shares = getShares();
    const conf = generateSmbConf(config, shares);
    return { conf };
  }

  // PUT /api/smb/share/:name — toggle SMB on a share (admin only)
  const shareToggle = url.match(/^\/api\/smb\/share\/([a-zA-Z0-9_-]+)$/);
  if (shareToggle && method === 'PUT') {
    if (session.role !== 'admin') return { error: 'Admin required' };
    const name = shareToggle[1];
    const shares = getShares();
    const share = shares.find(s => s.name === name);
    if (!share) return { error: 'Share not found' };
    
    share.smb = body.enabled !== false;
    saveShares(shares);
    return { ok: true, name, smbEnabled: share.smb };
  }

  // POST /api/smb/sync-users — sync all NimbusOS users to Linux/Samba (admin only)
  if (url === '/api/smb/sync-users' && method === 'POST') {
    if (session.role !== 'admin') return { error: 'Admin required' };
    const users = getUsers();
    const results = [];
    for (const user of users) {
      ensureLinuxUser(user.username);
      // We can't recover plaintext passwords, so just ensure Linux user exists
      // Samba password must be set separately if user was created before this feature
      const linuxExists = !!run(`id "${user.username}" 2>/dev/null`);
      const smbExists = !!run(`sudo pdbedit -L 2>/dev/null | grep -q "^${user.username}:" && echo yes`);
      results.push({ 
        username: user.username, 
        linuxUser: linuxExists, 
        sambaUser: smbExists,
      });
    }
    // Also fix ownership on all share directories
    const shares = getShares();
    for (const share of shares) {
      if (fs.existsSync(share.path)) {
        run(`sudo chmod 2775 "${share.path}" 2>/dev/null`);
        // Add nimbus group
        run(`sudo chgrp nimbus "${share.path}" 2>/dev/null`);
      }
    }
    return { ok: true, users: results };
  }

  // POST /api/smb/set-password — set Samba password for a user (admin only)
  if (url === '/api/smb/set-password' && method === 'POST') {
    if (session.role !== 'admin') return { error: 'Admin required' };
    const { username, password } = body;
    if (!username || !password) return { error: 'Username and password required' };
    const ok = ensureSmbUser(username, password);
    return ok ? { ok: true } : { error: 'Failed to set SMB password' };
  }

  return null;
}

// ═══════════════════════════════════
// ═══════════════════════════════════
// Firewall / Port Management
// ═══════════════════════════════════

function getFirewallRules() {
  const rules = [];
  
  // Try iptables first
  const iptOutput = run('iptables -L INPUT -n --line-numbers 2>/dev/null');
  if (iptOutput) {
    const lines = iptOutput.split('\n').filter(l => l.match(/^\d+/));
    lines.forEach(line => {
      const parts = line.trim().split(/\s+/);
      if (parts.length >= 5) {
        const num = parts[0];
        const action = parts[1]; // ACCEPT, DROP, REJECT
        const proto = parts[2]; // tcp, udp, all
        const src = parts[4]; // source
        const dst = parts[5]; // destination
        // Extract port from remaining
        const dptMatch = line.match(/dpt:(\d+)/);
        const dptsMatch = line.match(/dpts:(\d+:\d+)/);
        const port = dptMatch ? dptMatch[1] : dptsMatch ? dptsMatch[1].replace(':', '-') : '*';
        
        rules.push({
          num: parseInt(num),
          action,
          protocol: proto,
          source: src === '0.0.0.0/0' ? 'Any' : src,
          destination: dst === '0.0.0.0/0' ? 'Any' : dst,
          port,
          raw: line.trim(),
        });
      }
    });
  }

  // Check if ufw is active
  const ufwStatus = run('ufw status numbered 2>/dev/null');
  const ufwActive = ufwStatus && ufwStatus.includes('Status: active');
  
  let ufwRules = [];
  if (ufwActive && ufwStatus) {
    const ufwLines = ufwStatus.split('\n').filter(l => l.match(/^\[\s*\d+\]/));
    ufwLines.forEach(line => {
      const numMatch = line.match(/^\[\s*(\d+)\]/);
      const num = numMatch ? parseInt(numMatch[1]) : 0;
      
      const actionMatch = line.match(/\b(ALLOW|DENY|REJECT|LIMIT)\b/i);
      const action = actionMatch ? actionMatch[1].toUpperCase() : 'ALLOW';
      
      // Parse port/proto
      const portMatch = line.match(/(\d+(?::\d+)?)\/(tcp|udp)/i);
      const port = portMatch ? portMatch[1].replace(':', '-') : '*';
      const proto = portMatch ? portMatch[2] : 'any';
      
      // Parse source
      const inMatch = line.match(/\bIN\b/i);
      const fromMatch = line.match(/from\s+(\S+)/i);
      const source = fromMatch ? fromMatch[1] : 'Anywhere';

      ufwRules.push({ num, action, protocol: proto, source, port, raw: line.trim() });
    });
  }

  // Detect backend (ufw, iptables, nftables)
  const hasUfw = !!run('which ufw 2>/dev/null');
  const hasNft = !!run('which nft 2>/dev/null');
  const backend = ufwActive ? 'ufw' : hasUfw ? 'ufw (inactive)' : hasNft ? 'nftables' : 'iptables';

  return {
    backend,
    ufwActive,
    rules: ufwActive ? ufwRules : rules,
    defaultPolicy: ufwActive 
      ? (ufwStatus.includes('Default: deny') ? 'deny' : 'allow')
      : run('iptables -L INPUT 2>/dev/null | head -1')?.includes('DROP') ? 'deny' : 'allow',
  };
}

function getListeningPorts() {
  const ports = [];
  const ss = run('ss -tlnp 2>/dev/null') || run('netstat -tlnp 2>/dev/null');
  if (ss) {
    ss.split('\n').slice(1).filter(Boolean).forEach(line => {
      const parts = line.trim().split(/\s+/);
      if (parts.length < 5) return;
      const localAddr = parts[3] || '';
      const addrMatch = localAddr.match(/^(.*):(\d+)$/);
      if (!addrMatch) return;
      const addr = addrMatch[1];
      const port = parseInt(addrMatch[2]);
      const processInfo = parts.slice(5).join(' ');
      const procMatch = processInfo.match(/users:\(\("([^"]+)"/);
      const pidMatch = processInfo.match(/pid=(\d+)/);
      const process = procMatch ? procMatch[1] : '';
      const pid = pidMatch ? parseInt(pidMatch[1]) : null;
      if (port === 0) return;
      ports.push({
        port, address: addr === '*' || addr === '0.0.0.0' || addr === '::' ? '0.0.0.0' : addr,
        protocol: 'tcp', process, pid, exposed: addr === '*' || addr === '0.0.0.0' || addr === '::',
      });
    });
  }
  const ssUdp = run('ss -ulnp 2>/dev/null');
  if (ssUdp) {
    ssUdp.split('\n').slice(1).filter(Boolean).forEach(line => {
      const parts = line.trim().split(/\s+/);
      if (parts.length < 5) return;
      const localAddr = parts[3] || '';
      const addrMatch = localAddr.match(/^(.*):(\d+)$/);
      if (!addrMatch) return;
      const addr = addrMatch[1];
      const port = parseInt(addrMatch[2]);
      const processInfo = parts.slice(5).join(' ');
      const procMatch = processInfo.match(/users:\(\("([^"]+)"/);
      const pidMatch = processInfo.match(/pid=(\d+)/);
      const process = procMatch ? procMatch[1] : '';
      const pid = pidMatch ? parseInt(pidMatch[1]) : null;
      if (port === 0) return;
      ports.push({
        port, address: addr === '*' || addr === '0.0.0.0' || addr === '::' ? '0.0.0.0' : addr,
        protocol: 'udp', process, pid, exposed: addr === '*' || addr === '0.0.0.0' || addr === '::',
      });
    });
  }
  const seen = new Set();
  return ports.filter(p => {
    const key = `${p.port}/${p.protocol}/${p.address}`;
    if (seen.has(key)) return false;
    seen.add(key);
    return true;
  }).sort((a, b) => a.port - b.port);
}

function getFirewallScan() {
  const ports = getListeningPorts();
  const fw = getFirewallRules();
  
  // Detect docker containers and their port mappings
  const dockerPorts = [];
  const dockerPs = run('docker ps --format "{{.ID}}\\t{{.Names}}\\t{{.Image}}\\t{{.Ports}}" 2>/dev/null');
  if (dockerPs) {
    dockerPs.split('\n').filter(Boolean).forEach(line => {
      const [id, name, image, portsStr] = line.split('\t');
      if (!portsStr) return;
      // Parse "0.0.0.0:8080->80/tcp, :::8080->80/tcp" etc
      const portMappings = portsStr.split(',').map(s => s.trim());
      portMappings.forEach(mapping => {
        const m = mapping.match(/(?:(\d+\.\d+\.\d+\.\d+)|::):(\d+)->(\d+)\/(tcp|udp)/);
        if (m) {
          dockerPorts.push({
            hostPort: parseInt(m[2]),
            containerPort: parseInt(m[3]),
            protocol: m[4],
            containerName: name,
            containerImage: image,
            containerId: id,
          });
        }
      });
    });
  }

  // Known service labels
  const SERVICE_LABELS = {
    'node': 'Node.js', 'nginx': 'Nginx', 'apache2': 'Apache', 'httpd': 'Apache',
    'sshd': 'SSH', 'postgres': 'PostgreSQL', 'mysqld': 'MySQL', 'mariadbd': 'MariaDB',
    'redis-server': 'Redis', 'mongod': 'MongoDB', 'docker-proxy': 'Docker',
    'code-server': 'Code Server', 'java': 'Java', 'python3': 'Python', 'python': 'Python',
    'grafana': 'Grafana', 'prometheus': 'Prometheus', 'influxd': 'InfluxDB',
    'smbd': 'Samba (SMB)', 'named': 'DNS (BIND)', 'dnsmasq': 'DNS (dnsmasq)',
    'pihole-FTL': 'Pi-hole', 'jellyfin': 'Jellyfin', 'plex': 'Plex Media Server',
    'navidrome': 'Navidrome', 'syncthing': 'Syncthing', 'wireguard': 'WireGuard',
    'openvpn': 'OpenVPN', 'cups': 'CUPS (Printing)', 'avahi-daemon': 'Avahi (mDNS)',
    'unifi': 'UniFi Controller', 'homebridge': 'Homebridge',
  };

  // Build services list: group ports by process, cross-reference with fw rules & docker
  const groups = {};
  ports.forEach(p => {
    const docker = dockerPorts.find(d => d.hostPort === p.port && d.protocol === p.protocol);
    const key = docker ? `docker:${docker.containerName}` : (p.process || `unknown:${p.port}`);
    
    if (!groups[key]) {
      const label = docker
        ? docker.containerName
        : (SERVICE_LABELS[p.process] || p.process || 'Unknown');
      groups[key] = {
        name: label,
        process: p.process,
        isDocker: !!docker,
        containerName: docker?.containerName || null,
        containerImage: docker?.containerImage || null,
        ports: [],
      };
    }
    
    // Check if this port has a firewall ALLOW rule
    const isAllowed = fw.rules.some(r => {
      const rPort = String(r.port);
      const pPort = String(p.port);
      const actionOk = ['ALLOW', 'ACCEPT', 'LIMIT'].includes(r.action);
      if (rPort === pPort && actionOk) return true;
      // Range check "8000-8100"
      if (rPort.includes('-')) {
        const [lo, hi] = rPort.split('-').map(Number);
        if (p.port >= lo && p.port <= hi && actionOk) return true;
      }
      return false;
    });

    groups[key].ports.push({
      port: p.port,
      protocol: p.protocol,
      address: p.address,
      exposed: p.exposed,
      firewallAllowed: isAllowed,
    });
  });

  return {
    firewall: fw,
    services: Object.values(groups),
    dockerContainers: dockerPorts.length,
  };
}
// ═══════════════════════════════════
// UPnP Port Forwarding (Router)
// ═══════════════════════════════════

// SSDP discovery — find the router's UPnP control URL
function upnpDiscover(timeout = 3000) {
  return new Promise((resolve, reject) => {
    const SSDP_ADDR = '239.255.255.250';
    const SSDP_PORT = 1900;
    const searchTarget = 'urn:schemas-upnp-org:device:InternetGatewayDevice:1';
    
    const msg = Buffer.from(
      'M-SEARCH * HTTP/1.1\r\n' +
      `HOST: ${SSDP_ADDR}:${SSDP_PORT}\r\n` +
      'MAN: "ssdp:discover"\r\n' +
      'MX: 3\r\n' +
      `ST: ${searchTarget}\r\n` +
      '\r\n'
    );

    const sock = dgram.createSocket({ type: 'udp4', reuseAddr: true });
    let found = false;

    sock.on('message', (data) => {
      if (found) return;
      const response = data.toString();
      const locMatch = response.match(/LOCATION:\s*(.*?)\r\n/i);
      if (locMatch) {
        found = true;
        sock.close();
        resolve(locMatch[1].trim());
      }
    });

    sock.on('error', (err) => { sock.close(); reject(err); });
    sock.bind(() => {
      sock.addMembership(SSDP_ADDR);
      sock.send(msg, 0, msg.length, SSDP_PORT, SSDP_ADDR);
    });

    setTimeout(() => {
      if (!found) { sock.close(); reject(new Error('UPnP gateway not found')); }
    }, timeout);
  });
}

// Fetch XML from URL using http/https
function httpGet(url) {
  return new Promise((resolve, reject) => {
    const mod = url.startsWith('https') ? require('https') : require('http');
    mod.get(url, { timeout: 5000 }, (res) => {
      let data = '';
      res.on('data', c => data += c);
      res.on('end', () => resolve(data));
    }).on('error', reject);
  });
}

function httpPost(url, body, soapAction) {
  return new Promise((resolve, reject) => {
    const parsed = new URL(url);
    const mod = parsed.protocol === 'https:' ? require('https') : require('http');
    const options = {
      hostname: parsed.hostname, port: parsed.port, path: parsed.pathname,
      method: 'POST', timeout: 5000,
      headers: {
        'Content-Type': 'text/xml; charset="utf-8"',
        'Content-Length': Buffer.byteLength(body),
        'SOAPAction': `"${soapAction}"`,
      },
    };
    const req = mod.request(options, (res) => {
      let data = '';
      res.on('data', c => data += c);
      res.on('end', () => resolve({ status: res.statusCode, body: data }));
    });
    req.on('error', reject);
    req.write(body);
    req.end();
  });
}

// Parse router description XML to find WANIPConnection control URL
async function getControlUrl(descUrl) {
  const xml = await httpGet(descUrl);
  const parsed = new URL(descUrl);
  const baseUrl = `${parsed.protocol}//${parsed.host}`;
  
  // Look for WANIPConnection or WANPPPConnection service
  const serviceTypes = [
    'urn:schemas-upnp-org:service:WANIPConnection:1',
    'urn:schemas-upnp-org:service:WANPPPConnection:1',
    'urn:schemas-upnp-org:service:WANIPConnection:2',
  ];
  
  for (const st of serviceTypes) {
    const stIdx = xml.indexOf(st);
    if (stIdx === -1) continue;
    const ctrlMatch = xml.substring(stIdx).match(/<controlURL>(.*?)<\/controlURL>/i);
    if (ctrlMatch) {
      const ctrlPath = ctrlMatch[1];
      const serviceType = st;
      return { 
        controlUrl: ctrlPath.startsWith('http') ? ctrlPath : baseUrl + ctrlPath, 
        serviceType 
      };
    }
  }
  throw new Error('WANIPConnection service not found in router');
}

// Get external IP from router
async function upnpGetExternalIP(controlUrl, serviceType) {
  const body = `<?xml version="1.0"?>
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
  <s:Body><u:GetExternalIPAddress xmlns:u="${serviceType}"></u:GetExternalIPAddress></s:Body>
</s:Envelope>`;
  const res = await httpPost(controlUrl, body, `${serviceType}#GetExternalIPAddress`);
  const ipMatch = res.body.match(/<NewExternalIPAddress>(.*?)<\/NewExternalIPAddress>/i);
  return ipMatch ? ipMatch[1] : null;
}

// List existing port mappings
async function upnpListMappings(controlUrl, serviceType) {
  const mappings = [];
  for (let i = 0; i < 100; i++) {
    const body = `<?xml version="1.0"?>
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
  <s:Body><u:GetGenericPortMappingEntry xmlns:u="${serviceType}">
    <NewPortMappingIndex>${i}</NewPortMappingIndex>
  </u:GetGenericPortMappingEntry></s:Body>
</s:Envelope>`;
    try {
      const res = await httpPost(controlUrl, body, `${serviceType}#GetGenericPortMappingEntry`);
      if (res.status !== 200 || res.body.includes('SpecifiedArrayIndexInvalid') || res.body.includes('Fault')) break;
      
      const get = (tag) => { const m = res.body.match(new RegExp(`<${tag}>(.*?)</${tag}>`, 'i')); return m ? m[1] : ''; };
      mappings.push({
        externalPort: parseInt(get('NewExternalPort')) || 0,
        internalPort: parseInt(get('NewInternalPort')) || 0,
        internalClient: get('NewInternalClient'),
        protocol: get('NewProtocol'),
        description: get('NewPortMappingDescription'),
        enabled: get('NewEnabled') === '1',
        leaseDuration: parseInt(get('NewLeaseDuration')) || 0,
      });
    } catch { break; }
  }
  return mappings;
}

// Add a port mapping
async function upnpAddMapping(controlUrl, serviceType, externalPort, internalPort, protocol, internalClient, description, leaseDuration = 0) {
  const body = `<?xml version="1.0"?>
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
  <s:Body><u:AddPortMapping xmlns:u="${serviceType}">
    <NewRemoteHost></NewRemoteHost>
    <NewExternalPort>${externalPort}</NewExternalPort>
    <NewProtocol>${protocol.toUpperCase()}</NewProtocol>
    <NewInternalPort>${internalPort}</NewInternalPort>
    <NewInternalClient>${internalClient}</NewInternalClient>
    <NewEnabled>1</NewEnabled>
    <NewPortMappingDescription>${description}</NewPortMappingDescription>
    <NewLeaseDuration>${leaseDuration}</NewLeaseDuration>
  </u:AddPortMapping></s:Body>
</s:Envelope>`;
  const res = await httpPost(controlUrl, body, `${serviceType}#AddPortMapping`);
  if (res.status !== 200 && !res.body.includes('AddPortMappingResponse')) {
    const errMatch = res.body.match(/<errorDescription>(.*?)<\/errorDescription>/i);
    throw new Error(errMatch ? errMatch[1] : `UPnP error (HTTP ${res.status})`);
  }
  return true;
}

// Remove a port mapping
async function upnpRemoveMapping(controlUrl, serviceType, externalPort, protocol) {
  const body = `<?xml version="1.0"?>
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
  <s:Body><u:DeletePortMapping xmlns:u="${serviceType}">
    <NewRemoteHost></NewRemoteHost>
    <NewExternalPort>${externalPort}</NewExternalPort>
    <NewProtocol>${protocol.toUpperCase()}</NewProtocol>
  </u:DeletePortMapping></s:Body>
</s:Envelope>`;
  const res = await httpPost(controlUrl, body, `${serviceType}#DeletePortMapping`);
  if (res.status !== 200 && !res.body.includes('DeletePortMappingResponse')) {
    const errMatch = res.body.match(/<errorDescription>(.*?)<\/errorDescription>/i);
    throw new Error(errMatch ? errMatch[1] : `UPnP error (HTTP ${res.status})`);
  }
  return true;
}

// Get local IP for the interface that reaches the gateway
function getLocalIP() {
  const interfaces = os.networkInterfaces();
  for (const [name, addrs] of Object.entries(interfaces)) {
    for (const addr of addrs) {
      if (addr.family === 'IPv4' && !addr.internal && !name.startsWith('docker') && !name.startsWith('br-') && !name.startsWith('veth')) {
        return addr.address;
      }
    }
  }
  return '0.0.0.0';
}

// Cached UPnP gateway info (re-discover every 10 min)
let upnpCache = { controlUrl: null, serviceType: null, ts: 0 };
async function getUpnpGateway() {
  const now = Date.now();
  if (upnpCache.controlUrl && (now - upnpCache.ts) < 600000) return upnpCache;
  try {
    const descUrl = await upnpDiscover(4000);
    const { controlUrl, serviceType } = await getControlUrl(descUrl);
    upnpCache = { controlUrl, serviceType, ts: now, descUrl };
    return upnpCache;
  } catch (e) {
    throw new Error(`Router UPnP not available: ${e.message}`);
  }
}


module.exports = {
  handleSmb, handleSsh, handleDdns, handlePortal, handleProxy, handleFtp, handleNfs, handleDns,
  handleCerts, handleRemoteAccess, handleWebdav,
  getFirewallRules, getListeningPorts, getFirewallScan,
  upnpDiscover, getLocalIP, getUpnpGateway,
  upnpListMappings, upnpGetExternalIP, upnpAddMapping, upnpRemoveMapping,
};
